In [37]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv("data_cleaning.csv")
df

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.743,0.28900,1.01100,6.38300,0.07800,0.07800,1.152,NaN
1,112 Psc b,Confirmed,NaN,0.00500,0.00400,0.03300,0.00500,0.00400,NaN,NaN
2,112 Psc c,Confirmed,9.866,1.78100,3.19000,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,NaN,1.10000,1.10000,11.08730,1.10000,1.10000,NaN,NaN
4,14 And Ab,Confirmed,NaN,0.23000,0.23000,4.68400,0.23000,0.23000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
5981,YBP 401 b,Confirmed,NaN,0.05000,0.05000,0.46000,0.05000,0.05000,NaN,NaN
5982,YSES 2 b,Confirmed,6.300,0.90000,1.60000,NaN,NaN,NaN,NaN,NaN
5983,YZ Cet b,Confirmed,NaN,0.00028,0.00028,0.00220,0.00028,0.00028,NaN,NaN
5984,YZ Cet c,Confirmed,NaN,0.00035,0.00035,0.00359,0.00035,0.00035,NaN,NaN
5985,YZ Cet d,Confirmed,NaN,0.00038,0.00038,0.00343,0.00038,0.00038,NaN,NaN

# Initial Analysis

In [39]:
df.shape

(5986, 10)

In [40]:
df.head()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.743,0.289,1.011,6.3830,0.078,0.078,1.152,NaN
1,112 Psc b,Confirmed,NaN,0.005,0.004,0.0330,0.005,0.004,NaN,NaN
2,112 Psc c,Confirmed,9.866,1.781,3.190,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,NaN,1.100,1.100,11.0873,1.100,1.100,NaN,NaN
4,14 And Ab,Confirmed,NaN,0.230,0.230,4.6840,0.230,0.230,NaN,NaN

In [41]:
df.tail()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
5981,YBP 401 b,Confirmed,NaN,0.05000,0.05000,0.46000,0.05000,0.05000,NaN,NaN
5982,YSES 2 b,Confirmed,6.3,0.90000,1.60000,NaN,NaN,NaN,NaN,NaN
5983,YZ Cet b,Confirmed,NaN,0.00028,0.00028,0.00220,0.00028,0.00028,NaN,NaN
5984,YZ Cet c,Confirmed,NaN,0.00035,0.00035,0.00359,0.00035,0.00035,NaN,NaN
5985,YZ Cet d,Confirmed,NaN,0.00038,0.00038,0.00343,0.00038,0.00038,NaN,NaN

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5986 non-null   object
 1   planet_status        5986 non-null   object
 2   mass                 2079 non-null   float64
 3   mass_error_min       2817 non-null   float64
 4   mass_error_max       2817 non-null   float64
 5   mass_sini            1202 non-null   float64
 6   mass_sini_error_min  1039 non-null   float64
 7   mass_sini_error_max  1039 non-null   float64
 8   radius               4568 non-null   float64
 9   radius_error_min     4093 non-null   float64
dtypes: float64(8), object(2)
memory usage: 467.8+ KB

# Data Cleaning

In [43]:
df.isna().sum()

name                      0
planet_status             0
mass                   3907
mass_error_min         3169
mass_error_max         3169
mass_sini              4784
mass_sini_error_min    4947
mass_sini_error_max    4947
radius                 1418
radius_error_min       1893
dtype: int64

In [45]:
# replacing any invalid infinite values with NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
Q1 = df["radius"].quantile(0.25)
Q3 = df["radius"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["radius"] < lower) | (df["radius"] > upper)]

len(outliers)

876

# Statistical Analysis

In [48]:
df.describe()

,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
count,2079.000000,2817.000000,2808.000000,1202.000000,1039.000000,1039.000000,4568.000000,4093.000000
mean,1.492538,0.324366,0.678277,1.983529,0.214687,0.240453,0.401515,0.048986
std,2.602286,1.351929,16.163055,3.199717,0.636474,0.945468,0.430601,0.754220
min,0.000190,0.000000,-17.800000,0.000470,0.000000,0.000000,0.025430,0.000000
25%,0.029655,0.006290,0.005700,0.045000,0.005940,0.005300,0.145000,0.010000
50%,0.370000,0.041000,0.040000,0.731500,0.049300,0.050000,0.219000,0.020000
75%,1.466500,0.170000,0.168650,2.400000,0.170000,0.170000,0.384000,0.042000
max,12.934000,53.500000,850.000000,50.000000,13.000000,20.900000,6.900000,48.000000

In [49]:
df.mean(numeric_only=True)

mass                   1.492538
mass_error_min         0.324366
mass_error_max         0.678277
mass_sini              1.983529
mass_sini_error_min    0.214687
mass_sini_error_max    0.240453
radius                 0.401515
radius_error_min       0.048986
dtype: float64

In [50]:
df.median(numeric_only=True)

mass                   0.3700
mass_error_min         0.0410
mass_error_max         0.0400
mass_sini              0.7315
mass_sini_error_min    0.0493
mass_sini_error_max    0.0500
radius                 0.2190
radius_error_min       0.0200
dtype: float64

# Saving the Output

In [51]:
df.to_csv("cleaned_data.csv", index=False)